language: node_js
node_js:
	- 0.10
before_script:
	- sudo apt-key adv --keyserver hkp:keyserver.ubuntu.com:80 --recv 7F0CEB10
	- echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.lis
	- apt-get install -q=2 --force-yes mongodb-org
	- npm install --silent -g grunt-cli
	- apt-get install g++ -q=2 --force-yes