language: node_js
node_js:
- 0.10
services:
- mongodb
before_script:
- npm install --silent -g grunt-cli
- mongo NodeWebsite --eval 'db.createCollection("users")'
- mongo NodeWebsite --eval "db.users.insert({username:'admin',passwd:'admin'}"